GET http://localhost:8080


###
GET http://localhost:8080/users/1/businesses

###
DELETE http://localhost:8080/books/1


###
POST http://localhost:8080/restrictions
Content-Type: application/json
Authorization: Basic hihi@gmail.com Tester123

{ 
    "category": "managing arrival",
    "description":"testing 345345",
    "locationSetting": "outdoor"
}
###

###
PUT http://localhost:8080/restrictions/2
Content-Type: application/json
Authorization: Basic hihi@gmail.com:Tester123

{

    "description": "The Return of the King"

}

###
POST http://localhost:8080/users/1/businesses
Content-Type: application/json
Authorization: Basic hihi@gmail.com:Tester123

{
    "businessName":"turks kebab",
    "category":"better than pasta express",
    "outdoorIndoor":"o",
    "capacity":"1000"
}
###
PUT http://localhost:8080/users/1/businesses/1
Content-Type: application/json
Authorization: Basic hihi@gmail.com:Tester123

{
    "category":"best kebab",
    "outdoorIndoor":"O"
}

###
###

DELETE http://localhost:8080/users/1/businesses/1
Authorization: Basic hihi@gmail.com:Tester123

###
GET http://localhost:8080/books/1/reviews

###
POST http://localhost:8080/books/2/reviews
Content-Type: application/json
Authorization: Basic gooduser:goodpassword

{
    "review": "Terrible book :)"
}

###
PUT http://localhost:8080/books/2/reviews/2
Content-Type: application/json

{
    "review": "Should be bad!"
}

###
DELETE http://localhost:8080/restrictions/2

###

GET http://localhost:8080/users/search
Content-Type: application/json
# Authorization:Basic hihi4@gmail.com:Tester123

{
    "username":"hihi@gmail.com",
    "password":"Tester123"
}
###
POST http://localhost:8080/restrictions
Content-Type: application/json
Authorization: Basic hihi@gmail.com:Tester123

{
        "locationSetting":"Indoors",
        "category" : "Managing Arrivals",
        "description" : "nimama"
}

###
POST http://localhost:8080/users
Content-Type: application/json


{
        "username":"hihi4@gmail.com",
        "password": "Tester123",
        "firstName":"firstName",
        "lastName": "lastName",
        "authorities": "ROLE_USER"
}

###
PUT http://localhost:8080/users/2
Content-Type: application/json

{
    "password": "Testing12345",
    "firstName": "firstname",
    "lastName": "lasterName"
}

###

###
DELETE http://localhost:8080/users/2

###